"""
Recommendation Engine

Aggregates recommendations from all rule categories and returns
a prioritized list sorted by severity.
"""

from services.recommendations.rules import RecommendationRules


class RecommendationEngine:
    """
    Generates actionable recommendations based on the completed
    infrastructure analysis report.
    """

    SEVERITY_ORDER = {
        "Critical": 0,
        "High": 1,
        "Medium": 2,
        "Low": 3,
        "Info": 4
    }

    def __init__(self, report: dict):
        """
        Parameters
        ----------
        report : dict
            Complete report generated by InfrastructureAnalyzer.
        """
        self.report = report

    def generate(self):
        """
        Generate all recommendations.

        Returns
        -------
        list[Recommendation]
        """

        recommendations = []

        # SSL
        recommendations.extend(
            RecommendationRules.ssl(self.report)
        )
        print("SSL:", len(recommendations))

        # Security Headers
        recommendations.extend(
            RecommendationRules.headers(self.report)
        )
        print("Headers:", len(recommendations))

        # HTTP
        recommendations.extend(
            RecommendationRules.http(self.report)
        )

        # DNS
        recommendations.extend(
            RecommendationRules.dns(self.report)
        )

        # Email Security
        recommendations.extend(
            RecommendationRules.email(self.report)
        )

        # IP Hosting
        recommendations.extend(
            RecommendationRules.hosting(self.report)
        )

        # Sort by severity
        recommendations.sort(
            key=lambda recommendation: self.SEVERITY_ORDER.get(
                recommendation.severity,
                999
            )
        )

        return recommendations

    def summary(self, recommendations):
        """
        Generate a recommendation summary.

        Parameters
        ----------
        recommendations : list[Recommendation]

        Returns
        -------
        dict
        """

        summary = {
            "total": len(recommendations),
            "critical": 0,
            "high": 0,
            "medium": 0,
            "low": 0,
            "info": 0,
        }

        for recommendation in recommendations:

            severity = recommendation.severity.lower()

            if severity in summary:
                summary[severity] += 1

        return summary